version: 2

seeds:
  - name: raw_product
    description: "Raw product data from various e-commerce sources"
    columns:
      - name: product_name
        description: "The name of the product."
        data_type: string
      - name: sale_price
        description: "The sale price of the product."
        data_type: int64
      - name: ingest_timestamp_utc
        description: "The UTC timestamp string when the data was ingested."
        data_type: string # Treat as string in the seed
      - name: ecommerce_name
        description: "The name of the e-commerce platform."
        data_type: string
